#!/usr/bin/env bash
# GENERATED by lfs_extract.py from the LFS book (commands are MIT-licensed).
# Chapter slice: 'Chapter 8.' .. 'Chapter 9.'
# REVIEW before running: optional/alternative blocks and 'make check' lines are
# included verbatim; decide per package what you actually want. Do not run blind.
# ==========================================================================
# REVIEW BEFORE AN UNATTENDED RUN
# Faithful extraction of the book's Chapter-8 flow: each package is auto-
# unpacked/cd'd/cleaned, admonition (Note/Important) blocks are omitted, and the
# informational 8.1/8.2 sections are dropped. The lines below are the book's own
# interactive / placeholder / test steps; under 'set -euo pipefail' they will
# stop the run until you edit them:
#   [TEST-HALT  ] 8.5.1. Installation of Glibc make check
#   [DIAG-HALT  ] 8.5.1. Installation of Glibc grep "Timed out" $(find -name \*.out)
#   [INTERACTIVE] 8.5.2. Configuring Glibc tzselect
#   [PLACEHOLDER] 8.5.2. Configuring Glibc ln -sfv /usr/share/zoneinfo/<xxx> /etc/localtime
#   [TEST-HALT  ] 8.6.1. Installation of Zlib make check
#   [TEST-HALT  ] 8.8.1. Installation of Xz make check
#   [TEST-HALT  ] 8.9.1. Installation of Lz4 make -j1 check
#   [TEST-HALT  ] 8.10.1. Installation of Zstd make check
#   [TEST-HALT  ] 8.11.1. Installation of File make check
#   [TEST-HALT  ] 8.13.1. Installation of Pcre2 make check
#   [TEST-HALT  ] 8.14.1. Installation of M4 make check
#   [TEST-HALT  ] 8.15.1. Installation of Bc make test
#   [TEST-HALT  ] 8.16.1. Installation of Flex make check
#   [TEST-HALT  ] 8.18.1. Installation of Expect make test
#   [TEST-HALT  ] 8.19.1. Installation of DejaGNU make check
#   [TEST-HALT  ] 8.22.1. Installation of Binutils make -k check
#   [TEST-HALT  ] 8.23.1. Installation of GMP make check
#   [TEST-HALT  ] 8.24.1. Installation of MPFR make check
#   [TEST-HALT  ] 8.25.1. Installation of MPC make check
#   [TEST-HALT  ] 8.26.1. Installation of Attr make check
#   [TEST-HALT  ] 8.27.1. Installation of Acl make check
#   [TEST-HALT  ] 8.28.1. Installation of Libcap make test
#   [TEST-HALT  ] 8.29.1. Installation of Libxcrypt make check
#   [INTERACTIVE] 8.30.3. Setting the Root Password passwd root
#   [TEST-HALT  ] 8.35.1. Installation of Psmisc make check
#   [TEST-HALT  ] 8.36.1. Installation of Gettext make check
#   [TEST-HALT  ] 8.37.1. Installation of Bison make check
#   [TEST-HALT  ] 8.38.1. Installation of Grep make check
#   [TEST-HALT  ] 8.40.1. Installation of Libtool make check
#   [TEST-HALT  ] 8.41.1. Installation of GDBM make check
#   [TEST-HALT  ] 8.42.1. Installation of Gperf make check
#   [TEST-HALT  ] 8.43.1. Installation of Expat make check
#   [TEST-HALT  ] 8.44.1. Installation of Inetutils make check
#   [TEST-HALT  ] 8.45.1. Installation of Less make check
#   [TEST-HALT  ] 8.47.1. Installation of Autoconf make check
#   [TEST-HALT  ] 8.48.1. Installation of Automake make -j$(($(nproc)>4?$(nproc):4)) check
#   [TEST-HALT  ] 8.49.1. Installation of OpenSSL make test
#   [TEST-HALT  ] 8.50.1. Installation of Libelf make -k check
#   [TEST-HALT  ] 8.51.1. Installation of Libffi make check
#   [TEST-HALT  ] 8.54.1. Installation of Python 3 make test TESTOPTS="--timeout 120"
#   [TEST-HALT  ] 8.61.1. Installation of Coreutils make NON_ROOT_USERNAME=tester check-root
#   [TEST-HALT  ] 8.62.1. Installation of Diffutils make check
#   [PLACEHOLDER] 8.64.1. Installation of Groff PAGE=<paper_size> ./configure --prefix=/usr
#   [TEST-HALT  ] 8.64.1. Installation of Groff make check
#   [TEST-HALT  ] 8.66.1. Installation of Gzip make check
#   [TEST-HALT  ] 8.68.1. Installation of Kbd make check
#   [TEST-HALT  ] 8.71.1. Installation of Patch make check
#   [TEST-HALT  ] 8.72.1. Installation of Tar make check
#   [TEST-HALT  ] 8.73.1. Installation of Texinfo make check
#   [TEST-HALT  ] 8.79.1. Installation of Man-DB make check
#   [TEST-HALT  ] 8.82.1. Installation of E2fsprogs make check
# ==========================================================================

set -euo pipefail


#----------------------------------------------------------------------
# 8.1. Introduction  [informational - omitted]
#----------------------------------------------------------------------

#----------------------------------------------------------------------
# 8.2. Package Management  [informational - omitted]
#----------------------------------------------------------------------

#----------------------------------------------------------------------
# 8.3. Man-pages-6.18  [unpack man-pages-6.18.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/man-pages-6.18.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.3.1. Installation of Man-pages
rm -v man3/crypt*

make -R GIT=false prefix=/usr install

#   8.3.2. Contents of Man-pages
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.4. Iana-Etc-20260805  [unpack iana-etc-20260805.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/iana-etc-20260805.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.4.1. Installation of Iana-Etc
cp -v services protocols /etc

#   8.4.2. Contents of Iana-Etc
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.5. Glibc-2.44  [unpack glibc-2.44.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/glibc-2.44.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.5.1. Installation of Glibc
patch -Np1 -i ../glibc-fhs-1.patch

patch -Np1 -i ../glibc-2.44-upstream_fixes-1.patch

mkdir -v build
cd       build

../configure --prefix=/usr                   \
             --disable-werror                \
             --disable-nscd                  \
             libc_cv_slibdir=/usr/lib        \
             --enable-stack-protector=strong \
             --enable-kernel=5.10

make

make check

grep "Timed out" $(find -name \*.out)

touch /etc/ld.so.conf

sed '/test-installation/s@$(PERL)@echo not running@' -i ../Makefile

make install

sed '/RTLDLIST=/s@/usr@@g' -i /usr/bin/ldd

localedef -i C -f UTF-8 C.UTF-8
localedef -i cs_CZ -f UTF-8 cs_CZ.UTF-8
localedef -i de_DE -f ISO-8859-1 de_DE
localedef -i de_DE@euro -f ISO-8859-15 de_DE@euro
localedef -i de_DE -f UTF-8 de_DE.UTF-8
localedef -i el_GR -f ISO-8859-7 el_GR
localedef -i en_GB -f ISO-8859-1 en_GB
localedef -i en_GB -f UTF-8 en_GB.UTF-8
localedef -i en_HK -f ISO-8859-1 en_HK
localedef -i en_PH -f ISO-8859-1 en_PH
localedef -i en_US -f ISO-8859-1 en_US
localedef -i en_US -f UTF-8 en_US.UTF-8
localedef -i es_ES -f ISO-8859-15 es_ES@euro
localedef -i es_MX -f ISO-8859-1 es_MX
localedef -i fa_IR -f UTF-8 fa_IR
localedef -i fr_FR -f ISO-8859-1 fr_FR
localedef -i fr_FR@euro -f ISO-8859-15 fr_FR@euro
localedef -i fr_FR -f UTF-8 fr_FR.UTF-8
localedef -i is_IS -f ISO-8859-1 is_IS
localedef -i is_IS -f UTF-8 is_IS.UTF-8
localedef -i it_IT -f ISO-8859-1 it_IT
localedef -i it_IT -f ISO-8859-15 it_IT@euro
localedef -i it_IT -f UTF-8 it_IT.UTF-8
localedef -i ja_JP -f EUC-JP ja_JP
localedef -i ja_JP -f UTF-8 ja_JP.UTF-8
localedef -i nl_NL@euro -f ISO-8859-15 nl_NL@euro
localedef -i ru_RU -f KOI8-R ru_RU.KOI8-R
localedef -i ru_RU -f UTF-8 ru_RU.UTF-8
localedef -i se_NO -f UTF-8 se_NO.UTF-8
localedef -i ta_IN -f UTF-8 ta_IN.UTF-8
localedef -i tr_TR -f UTF-8 tr_TR.UTF-8
localedef -i zh_CN -f GB18030 zh_CN.GB18030
localedef -i zh_HK -f BIG5-HKSCS zh_HK.BIG5-HKSCS
localedef -i zh_TW -f UTF-8 zh_TW.UTF-8

make localedata/install-locales

#   8.5.2. Configuring Glibc
cat > /etc/nsswitch.conf << "EOF"
# Begin /etc/nsswitch.conf

passwd: files systemd
group: files systemd
shadow: files systemd

hosts: mymachines resolve [!UNAVAIL=return] files myhostname dns
networks: files

protocols: files
services: files
ethers: files
rpc: files

# End /etc/nsswitch.conf
EOF

tar -xf ../../tzdata2026c.tar.gz

ZONEINFO=/usr/share/zoneinfo
mkdir -pv $ZONEINFO/{posix,right}

for tz in etcetera southamerica northamerica europe africa antarctica  \
          asia australasia backward; do
    zic -L /dev/null   -d $ZONEINFO       ${tz}
    zic -L /dev/null   -d $ZONEINFO/posix ${tz}
    zic -L leapseconds -d $ZONEINFO/right ${tz}
done

cp -v zone.tab zone1970.tab iso3166.tab $ZONEINFO
zic -d $ZONEINFO -p America/New_York
unset ZONEINFO tz

tzselect

ln -sfv /usr/share/zoneinfo/<xxx> /etc/localtime

cat > /etc/ld.so.conf << "EOF"
# Begin /etc/ld.so.conf
/usr/local/lib
/opt/lib

EOF

cat >> /etc/ld.so.conf << "EOF"
# Add an include directory
include /etc/ld.so.conf.d/*.conf

EOF
mkdir -pv /etc/ld.so.conf.d

#   8.5.3. Contents of Glibc
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.6. Zlib-1.3.2  [unpack zlib-1.3.2.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/zlib-1.3.2.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.6.1. Installation of Zlib
./configure --prefix=/usr

make

make check

make install

rm -fv /usr/lib/libz.a

#   8.6.2. Contents of Zlib
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.7. Bzip2-1.0.8  [unpack bzip2-1.0.8.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/bzip2-1.0.8.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.7.1. Installation of Bzip2
patch -Np1 -i ../bzip2-1.0.8-install_docs-1.patch

sed -i 's@\(ln -s -f \)$(PREFIX)/bin/@\1@' Makefile

sed -i "s@(PREFIX)/man@(PREFIX)/share/man@g" Makefile

make -f Makefile-libbz2_so
make clean

make

make PREFIX=/usr install

cp -av libbz2.so.* /usr/lib
ln -sfv libbz2.so.1.0.8 /usr/lib/libbz2.so

ln -sfv libbz2.so.1.0.8 /usr/lib/libbz2.so.1

cp -v bzip2-shared /usr/bin/bzip2
for i in /usr/bin/{bzcat,bunzip2}; do
  ln -sfv bzip2 $i
done

rm -fv /usr/lib/libbz2.a

#   8.7.2. Contents of Bzip2
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.8. Xz-5.8.3  [unpack xz-5.8.3.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/xz-5.8.3.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.8.1. Installation of Xz
./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/xz-5.8.3

make

make check

make install

#   8.8.2. Contents of Xz
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.9. Lz4-1.10.0  [unpack lz4-1.10.0.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/lz4-1.10.0.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.9.1. Installation of Lz4
make BUILD_STATIC=no PREFIX=/usr

make -j1 check

make BUILD_STATIC=no PREFIX=/usr install

#   8.9.2. Contents of Lz4
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.10. Zstd-1.5.7  [unpack zstd-1.5.7.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/zstd-1.5.7.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.10.1. Installation of Zstd
make prefix=/usr

make check

make prefix=/usr install

rm -v /usr/lib/libzstd.a

#   8.10.2. Contents of Zstd
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.11. File-5.48  [unpack file-5.48.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/file-5.48.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.11.1. Installation of File
./configure --prefix=/usr

make

make check

make install

#   8.11.2. Contents of File
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.12. Readline-8.3  [unpack readline-8.3.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/readline-8.3.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.12.1. Installation of Readline
sed -i '/MV.*old/d' Makefile.in
sed -i '/{OLDSUFF}/c:' support/shlib-install

sed -i 's/-Wl,-rpath,[^ ]*//' support/shobj-conf

sed -e '270a\
     else\
       chars_avail = 1;'      \
    -e '288i\   result = -1;' \
    -i.orig input.c

./configure --prefix=/usr    \
            --disable-static \
            --with-curses    \
            --docdir=/usr/share/doc/readline-8.3

make SHLIB_LIBS="-lncursesw"

make install

install -v -m644 doc/*.{ps,pdf,html,dvi} /usr/share/doc/readline-8.3

#   8.12.2. Contents of Readline
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.13. Pcre2-10.47  [unpack pcre2-10.47.tar.bz2]
#----------------------------------------------------------------------
_tb="/sources/pcre2-10.47.tar.bz2"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.13.1. Installation of Pcre2
./configure --prefix=/usr                       \
            --docdir=/usr/share/doc/pcre2-10.47 \
            --enable-unicode                    \
            --enable-jit                        \
            --enable-pcre2-16                   \
            --enable-pcre2-32                   \
            --enable-pcre2grep-libz             \
            --enable-pcre2grep-libbz2           \
            --enable-pcre2test-libreadline      \
            --disable-static

make

make check

make install

#   8.13.2. Contents of Pcre2
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.14. M4-1.4.21  [unpack m4-1.4.21.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/m4-1.4.21.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.14.1. Installation of M4
./configure --prefix=/usr

make

make check

make install

#   8.14.2. Contents of M4
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.15. Bc-7.0.3  [unpack bc-7.0.3.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/bc-7.0.3.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.15.1. Installation of Bc
CC='gcc -std=c99' ./configure --prefix=/usr -G -O3 -r

make

make test

make install

#   8.15.2. Contents of Bc
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.16. Flex-2.6.4  [unpack flex-2.6.4.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/flex-2.6.4.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.16.1. Installation of Flex
./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/flex-2.6.4

make

make check

make install

ln -sv flex   /usr/bin/lex
ln -sv flex.1 /usr/share/man/man1/lex.1

#   8.16.2. Contents of Flex
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.17. Tcl-8.6.18  [unpack tcl8.6.18-html.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/tcl8.6.18-html.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.17.1. Installation of Tcl
SRCDIR=$(pwd)
cd unix
./configure --prefix=/usr           \
            --mandir=/usr/share/man \
            --disable-rpath

make

sed -e "s|$SRCDIR/unix|/usr/lib|" \
    -e "s|$SRCDIR|/usr/include|"  \
    -i tclConfig.sh

sed -e "s|$SRCDIR/unix/pkgs/tdbc1.1.13|/usr/lib/tdbc1.1.13|" \
    -e "s|$SRCDIR/pkgs/tdbc1.1.13/generic|/usr/include|"     \
    -e "s|$SRCDIR/pkgs/tdbc1.1.13/library|/usr/lib/tcl8.6|"  \
    -e "s|$SRCDIR/pkgs/tdbc1.1.13|/usr/include|"             \
    -i pkgs/tdbc1.1.13/tdbcConfig.sh

sed -e "s|$SRCDIR/unix/pkgs/itcl4.3.7|/usr/lib/itcl4.3.7|" \
    -e "s|$SRCDIR/pkgs/itcl4.3.7/generic|/usr/include|"    \
    -e "s|$SRCDIR/pkgs/itcl4.3.7|/usr/include|"            \
    -i pkgs/itcl4.3.7/itclConfig.sh

unset SRCDIR

LC_ALL=C.UTF-8 make test

make install 
chmod 644 /usr/lib/libtclstub8.6.a

chmod -v u+w /usr/lib/libtcl8.6.so

make install-private-headers

ln -sfv tclsh8.6 /usr/bin/tclsh

mv -v /usr/share/man/man3/{Thread,Tcl_Thread}.3

cd ..
tar -xf ../tcl8.6.18-html.tar.gz --strip-components=1
mkdir -v -p /usr/share/doc/tcl-8.6.18
cp -v -r  ./html/* /usr/share/doc/tcl-8.6.18

#   8.17.2. Contents of Tcl
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.18. Expect-5.45.4  [unpack expect5.45.4.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/expect5.45.4.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.18.1. Installation of Expect
python3 -c 'from pty import spawn; spawn(["echo", "ok"])'

patch -Np1 -i ../expect-5.45.4-gcc15-1.patch

./configure --prefix=/usr           \
            --with-tcl=/usr/lib     \
            --enable-shared         \
            --disable-rpath         \
            --mandir=/usr/share/man \
            --with-tclinclude=/usr/include

make

make test

make install
ln -svf expect5.45.4/libexpect5.45.4.so /usr/lib

#   8.18.2. Contents of Expect
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.19. DejaGNU-1.6.3  [unpack dejagnu-1.6.3.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/dejagnu-1.6.3.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.19.1. Installation of DejaGNU
mkdir -v build
cd       build

../configure --prefix=/usr
makeinfo --html --no-split -o doc/dejagnu.html ../doc/dejagnu.texi
makeinfo --plaintext       -o doc/dejagnu.txt  ../doc/dejagnu.texi

make check

make install
install -v -dm755  /usr/share/doc/dejagnu-1.6.3
install -v -m644   doc/dejagnu.{html,txt} /usr/share/doc/dejagnu-1.6.3

#   8.19.2. Contents of DejaGNU
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.20. Ninja-1.13.2  [unpack ninja-1.13.2.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/ninja-1.13.2.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.20.1. Installation of Ninja
sed -i '/int Guess/a \
  int   j = 0;\
  char* jobs = getenv( "NINJAJOBS" );\
  if ( jobs != NULL ) j = atoi( jobs );\
  if ( j > 0 ) return j;\
' src/ninja.cc

python3 configure.py --bootstrap --verbose

install -vm755 ninja /usr/bin/
install -vDm644 misc/bash-completion /usr/share/bash-completion/completions/ninja
install -vDm644 misc/zsh-completion  /usr/share/zsh/site-functions/_ninja

#   8.20.2. Contents of Ninja
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.21. Pkgconf-3.0.5  [unpack pkgconf-3.0.5.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/pkgconf-3.0.5.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.21.1. Installation of Pkgconf
tar -xf ../meson-1.12.0.tar.gz

mkdir build
cd    build

python3 ../meson-1.12.0/meson.py setup --prefix=/usr --buildtype=release ..

ninja

ninja test

ninja install
mv /usr/share/doc/pkgconf{,-3.0.5}

ln -sv pkgconf   /usr/bin/pkg-config
ln -sv pkgconf.1 /usr/share/man/man1/pkg-config.1

#   8.21.2. Contents of Pkgconf
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.22. Binutils-2.47  [unpack binutils-2.47.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/binutils-2.47.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.22.1. Installation of Binutils
mkdir -v build
cd       build

../configure --prefix=/usr       \
             --sysconfdir=/etc   \
             --enable-ld=default \
             --enable-plugins    \
             --enable-shared     \
             --disable-werror    \
             --enable-64-bit-bfd \
             --enable-new-dtags  \
             --with-system-zlib  \
             --with-lib-path=/usr/lib \
             --enable-default-hash-style=gnu

make tooldir=/usr

make -k check

grep '^FAIL:' $(find -name '*.log')

make tooldir=/usr install

rm -rfv /usr/lib/lib{bfd,ctf,ctf-nobfd,gprofng,opcodes,sframe}.a \
        /usr/share/doc/gprofng/

#   8.22.2. Contents of Binutils
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.23. GMP-6.3.0  [unpack gmp-6.3.0.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/gmp-6.3.0.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.23.1. Installation of GMP
sed -i '/long long t1;/,+1s/()/(...)/' configure

./configure --prefix=/usr    \
            --enable-cxx     \
            --disable-static \
            --docdir=/usr/share/doc/gmp-6.3.0

make
make html

make check

cat $(find -name '*.log') | grep -c ^PASS

make install
make install-html

#   8.23.2. Contents of GMP
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.24. MPFR-4.2.2  [unpack mpfr-4.2.2.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/mpfr-4.2.2.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.24.1. Installation of MPFR
./configure --prefix=/usr        \
            --disable-static     \
            --enable-thread-safe \
            --docdir=/usr/share/doc/mpfr-4.2.2

make
make html

make check

make install
make install-html

#   8.24.2. Contents of MPFR
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.25. MPC-1.4.1  [unpack mpc-1.4.1.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/mpc-1.4.1.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.25.1. Installation of MPC
./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/mpc-1.4.1

make
make html

make check

make install
make install-html

#   8.25.2. Contents of MPC
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.26. Attr-2.6.0  [unpack attr-2.6.0.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/attr-2.6.0.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.26.1. Installation of Attr
./configure --prefix=/usr     \
            --disable-static  \
            --sysconfdir=/etc \
            --docdir=/usr/share/doc/attr-2.6.0

make

make check

make install

#   8.26.2. Contents of Attr
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.27. Acl-2.4.0  [unpack acl-2.4.0.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/acl-2.4.0.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.27.1. Installation of Acl
./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/acl-2.4.0

make

make check

make install

#   8.27.2. Contents of Acl
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.28. Libcap-2.78  [unpack libcap-2.78.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/libcap-2.78.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.28.1. Installation of Libcap
sed -i '/install -m.*STA/d' libcap/Makefile

make prefix=/usr lib=lib

make test

make prefix=/usr lib=lib install

#   8.28.2. Contents of Libcap
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.29. Libxcrypt-4.5.2  [unpack libxcrypt-4.5.2.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/libxcrypt-4.5.2.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.29.1. Installation of Libxcrypt
sed -i '/strchr/s/const//' lib/crypt-{sm3,gost}-yescrypt.c

./configure --prefix=/usr                \
            --enable-hashes=strong,glibc \
            --enable-obsolete-api=no     \
            --disable-static             \
            --disable-failure-tokens

make

make check

make install

#   8.29.2. Contents of Libxcrypt
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.30. Shadow-4.20.2  [unpack shadow-4.20.2.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/shadow-4.20.2.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.30.1. Installation of Shadow
find man -name Makefile.in -exec sed -i 's/getspnam\.3 / /' {} \;
find man -name Makefile.in -exec sed -i 's/passwd\.5 / /'   {} \;

sed -e 's:#ENCRYPT_METHOD SHA512:ENCRYPT_METHOD YESCRYPT:' \
    -e 's:/var/spool/mail:/var/mail:'                      \
    -e '/PATH=/{s@/sbin:@@;s@/bin:@@}'                     \
    -i etc/login.defs

touch /usr/bin/passwd
./configure --sysconfdir=/etc   \
            --disable-static    \
            --with-{b,yes}crypt \
            --without-libbsd    \
            --disable-logind    \
            --with-group-name-max-length=32

make

make exec_prefix=/usr install
make -C man install-man

#   8.30.2. Configuring Shadow
pwconv

grpconv

mkdir -p /etc/default
useradd -D --gid 999

sed -i '/MAIL/s/yes/no/' /etc/default/useradd

touch /etc/sub{u,g}id

#   8.30.3. Setting the Root Password
passwd root

#   8.30.4. Contents of Shadow
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.31. Gawk-5.4.1  [unpack gawk-5.4.1.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/gawk-5.4.1.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.31.1. Installation of Gawk
sed -i 's/extras//' Makefile.in

./configure --prefix=/usr

make

chown -R tester .
su tester -c "PATH=$PATH make check"

rm -f /usr/bin/gawk-5.4.1
make install

ln -sv gawk.1 /usr/share/man/man1/awk.1

install -vDm644 doc/{awkforai.txt,*.{eps,pdf,jpg}} -t /usr/share/doc/gawk-5.4.1

#   8.31.2. Contents of Gawk
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.32. GCC-16.2.0  [unpack gcc-16.2.0.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/gcc-16.2.0.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.32.1. Installation of GCC
case $(uname -m) in
  x86_64)
    sed -e '/m64=/s/lib64/lib/' \
        -i.orig gcc/config/i386/t-linux64
  ;;
esac

mkdir -v build
cd       build

../configure --prefix=/usr            \
             LD=ld                    \
             --enable-languages=c,c++ \
             --enable-default-pie     \
             --enable-default-ssp     \
             --enable-host-pie        \
             --enable-targets=all     \
             --disable-multilib       \
             --disable-bootstrap      \
             --disable-fixincludes    \
             --with-system-zlib

make

ulimit -s -H unlimited

chown -R tester .
su tester -c "PATH=$PATH make -k check"

../contrib/test_summary -t

make install

chown -v -R root:root $(gcc -print-file-name=include){,-fixed}

ln -svr /usr/bin/cpp /usr/lib

ln -sv gcc.1 /usr/share/man/man1/cc.1

ln -sfvr $(gcc -print-prog-name=liblto_plugin.so) /usr/lib/bfd-plugins/

echo 'int main(){}' | cc -x c - -v -Wl,--verbose &> dummy.log
readelf -l a.out | grep ': /lib'

grep -E -o '/usr/lib.*/S?crt[1in].*succeeded' dummy.log

grep -B4 '^ /usr/include' dummy.log

grep 'SEARCH.*/usr/lib' dummy.log |sed 's|; |\n|g'

grep "/lib.*/libc.so.6 " dummy.log

grep found dummy.log

rm -v a.out dummy.log

mkdir -pv /usr/share/gdb/auto-load/usr/lib
mv -v /usr/lib/*gdb.py /usr/share/gdb/auto-load/usr/lib

#   8.32.2. Contents of GCC
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.33. Ncurses-6.6  [unpack ncurses-6.6.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/ncurses-6.6.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.33.1. Installation of Ncurses
./configure --prefix=/usr           \
            --mandir=/usr/share/man \
            --with-shared           \
            --without-debug         \
            --without-normal        \
            --with-cxx-shared       \
            --enable-pc-files       \
            --with-pkg-config-libdir=/usr/lib/pkgconfig

make

make DESTDIR=$PWD/dest install
sed -e 's/^#if.*XOPEN.*$/#if 1/' \
    -i dest/usr/include/curses.h
cp --remove-destination -av dest/* /

for lib in ncurses form panel menu ; do
    ln -sfv lib${lib}w.so /usr/lib/lib${lib}.so
    ln -sfv ${lib}w.pc    /usr/lib/pkgconfig/${lib}.pc
done

ln -sfv libncursesw.so /usr/lib/libcurses.so

cp -v -R doc -T /usr/share/doc/ncurses-6.6

#   8.33.2. Contents of Ncurses
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.34. Sed-4.10  [unpack sed-4.10.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/sed-4.10.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.34.1. Installation of Sed
./configure --prefix=/usr

make
make html

chown -R tester .
su tester -c "PATH=$PATH make check"

make install
install -vDm644 doc/sed.html -t /usr/share/doc/sed-4.10

#   8.34.2. Contents of Sed
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.35. Psmisc-23.7  [unpack psmisc-23.7.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/psmisc-23.7.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.35.1. Installation of Psmisc
./configure --prefix=/usr

make

make check

make install

#   8.35.2. Contents of Psmisc
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.36. Gettext-1.0  [unpack gettext-1.0.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/gettext-1.0.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.36.1. Installation of Gettext
./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/gettext-1.0

make

make check

make install
chmod -v 0755 /usr/lib/preloadable_libintl.so

#   8.36.2. Contents of Gettext
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.37. Bison-3.8.2  [unpack bison-3.8.2.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/bison-3.8.2.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.37.1. Installation of Bison
./configure --prefix=/usr --docdir=/usr/share/doc/bison-3.8.2

make

make check

make install

#   8.37.2. Contents of Bison
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.38. Grep-3.12  [unpack grep-3.12.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/grep-3.12.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.38.1. Installation of Grep
sed -i "s/echo/#echo/" src/egrep.sh

./configure --prefix=/usr

make

make check

make install

#   8.38.2. Contents of Grep
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.39. Bash-5.3  [unpack bash-5.3.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/bash-5.3.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.39.1. Installation of Bash
./configure --prefix=/usr             \
            --without-bash-malloc     \
            --with-installed-readline \
            --docdir=/usr/share/doc/bash-5.3

make

chown -R tester .

LC_ALL=C.UTF-8 su -s /usr/bin/expect tester << "EOF"
set timeout -1
spawn make tests
expect eof
lassign [wait] _ _ _ value
exit $value
EOF

make install

exec /usr/bin/bash --login

#   8.39.2. Contents of Bash
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.40. Libtool-2.6.2  [unpack libtool-2.6.2.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/libtool-2.6.2.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.40.1. Installation of Libtool
./configure --prefix=/usr

make

make check

make install

rm -fv /usr/lib/libltdl.a

#   8.40.2. Contents of Libtool
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.41. GDBM-1.26  [unpack gdbm-1.26.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/gdbm-1.26.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.41.1. Installation of GDBM
./configure --prefix=/usr    \
            --disable-static \
            --enable-libgdbm-compat

make

make check

make install

#   8.41.2. Contents of GDBM
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.42. Gperf-3.3  [unpack gperf-3.3.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/gperf-3.3.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.42.1. Installation of Gperf
./configure --prefix=/usr --docdir=/usr/share/doc/gperf-3.3

make

make check

make install

#   8.42.2. Contents of Gperf
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.43. Expat-2.8.3  [unpack expat-2.8.3.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/expat-2.8.3.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.43.1. Installation of Expat
./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/expat-2.8.3

make

make check

make install

install -v -m644 doc/*.{html,css} /usr/share/doc/expat-2.8.3

#   8.43.2. Contents of Expat
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.44. Inetutils-2.8  [unpack inetutils-2.8.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/inetutils-2.8.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.44.1. Installation of Inetutils
sed -i 's/def HAVE_TERMCAP_TGETENT/ 1/' telnet/telnet.c

./configure --prefix=/usr        \
            --bindir=/usr/bin    \
            --localstatedir=/var \
            --disable-logger     \
            --disable-whois      \
            --disable-rcp        \
            --disable-rexec      \
            --disable-rlogin     \
            --disable-rsh        \
            --disable-servers

make

make check

make install

mv -v /usr/{,s}bin/ifconfig

#   8.44.2. Contents of Inetutils
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.45. Less-704  [unpack less-704.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/less-704.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.45.1. Installation of Less
./configure --prefix=/usr --sysconfdir=/etc

make

make check

make install

#   8.45.2. Contents of Less
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.46. Perl-5.44.0  [unpack perl-5.44.0.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/perl-5.44.0.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.46.1. Installation of Perl
export BUILD_ZLIB=False
export BUILD_BZIP2=0

sh Configure -des                                          \
             -D prefix=/usr                                \
             -D vendorprefix=/usr                          \
             -D privlib=/usr/lib/perl5/5.44/core_perl      \
             -D archlib=/usr/lib/perl5/5.44/core_perl      \
             -D sitelib=/usr/lib/perl5/5.44/site_perl      \
             -D sitearch=/usr/lib/perl5/5.44/site_perl     \
             -D vendorlib=/usr/lib/perl5/5.44/vendor_perl  \
             -D vendorarch=/usr/lib/perl5/5.44/vendor_perl \
             -D man1dir=/usr/share/man/man1                \
             -D man3dir=/usr/share/man/man3                \
             -D pager="/usr/bin/less -isR"                 \
             -D useshrplib                                 \
             -D usethreads

make

TEST_JOBS=$(nproc) make test_harness

make install
unset BUILD_ZLIB BUILD_BZIP2

#   8.46.2. Contents of Perl
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.47. Autoconf-2.73  [unpack autoconf-2.73.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/autoconf-2.73.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.47.1. Installation of Autoconf
./configure --prefix=/usr

make

make check

make install

#   8.47.2. Contents of Autoconf
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.48. Automake-1.18.1  [unpack automake-1.18.1.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/automake-1.18.1.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.48.1. Installation of Automake
./configure --prefix=/usr --docdir=/usr/share/doc/automake-1.18.1

make

make -j$(($(nproc)>4?$(nproc):4)) check

make install

#   8.48.2. Contents of Automake
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.49. OpenSSL-4.0.1  [unpack openssl-4.0.1.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/openssl-4.0.1.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.49.1. Installation of OpenSSL
./config --prefix=/usr         \
         --openssldir=/etc/ssl \
         --libdir=lib          \
         shared                \
         zlib-dynamic

make

make test

make INSTALL_LIBS= MANSUFFIX=ssl install

mv -v /usr/share/doc/openssl /usr/share/doc/openssl-4.0.1

cp -vfr doc/* /usr/share/doc/openssl-4.0.1

#   8.49.2. Contents of OpenSSL
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.50. Libelf from Elfutils-0.195  [unpack elfutils-0.195.tar.bz2]
#----------------------------------------------------------------------
_tb="/sources/elfutils-0.195.tar.bz2"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.50.1. Installation of Libelf
./configure --prefix=/usr        \
            --disable-debuginfod \
            --enable-libdebuginfod=dummy

make -C lib
make -C libelf

make -k check

make -C libelf install
install -vm644 config/libelf.pc /usr/lib/pkgconfig
rm /usr/lib/libelf.a

#   8.50.2. Contents of Libelf
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.51. Libffi-3.8.0  [unpack libffi-3.8.0.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/libffi-3.8.0.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.51.1. Installation of Libffi
./configure --prefix=/usr    \
            --disable-static \
            --with-gcc-arch=native

make

make check

make install

#   8.51.2. Contents of Libffi
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.52. Sqlite-3530400  [unpack sqlite-autoconf-3530400.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/sqlite-autoconf-3530400.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.52.1. Installation of Sqlite
python3 -m zipfile -e ../sqlite-doc-3530400.zip .

./configure --prefix=/usr     \
            --disable-static  \
            --enable-fts{4,5} \
            CPPFLAGS="-D SQLITE_ENABLE_COLUMN_METADATA=1 \
                      -D SQLITE_ENABLE_UNLOCK_NOTIFY=1   \
                      -D SQLITE_ENABLE_DBSTAT_VTAB=1     \
                      -D SQLITE_SECURE_DELETE=1"

make LDFLAGS.rpath=""

make install

cp -v -R sqlite-doc-3530400 -T /usr/share/doc/sqlite-3.53.4

#   8.52.2. Contents of Sqlite
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.53. mpdecimal-4.0.1  [unpack mpdecimal-4.0.1.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/mpdecimal-4.0.1.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.53.1. Installation of mpdecimal
./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/mpdecimal-4.0.1

make

make check_local

make install

#   8.53.2. Contents of mpdecimal
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.54. Python-3.14.7  [unpack Python-3.14.7.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/Python-3.14.7.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.54.1. Installation of Python 3
patch -Np1 -i ../Python-3.14.7-openssl_4-1.patch

./configure --prefix=/usr          \
            --enable-shared        \
            --with-system-expat    \
            --enable-optimizations \
            --without-static-libpython

make

make test TESTOPTS="--timeout 120"

make install

cat > /etc/pip.conf << EOF
[global]
root-user-action = ignore
disable-pip-version-check = true
EOF

install -v -dm755 /usr/share/doc/python-3.14.7/html

tar --strip-components=1  \
    --no-same-owner       \
    --no-same-permissions \
    -C /usr/share/doc/python-3.14.7/html \
    -xvf ../python-3.14.7-docs-html.tar.bz2

#   8.54.2. Contents of Python 3
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.55. Flit-Core-4.0.2  [unpack flit_core-4.0.2.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/flit_core-4.0.2.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.55.1. Installation of Flit-Core
pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD

pip3 install --no-index --find-links dist flit_core

#   8.55.2. Contents of Flit-Core
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.56. Packaging-26.3  [unpack packaging-26.3.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/packaging-26.3.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.56.1. Installation of Packaging
pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD

pip3 install --no-index --find-links dist packaging

#   8.56.2. Contents of Packaging
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.57. Wheel-0.48.0  [unpack wheel-0.48.0.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/wheel-0.48.0.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.57.1. Installation of Wheel
pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD

pip3 install --no-index --find-links dist wheel

#   8.57.2. Contents of Wheel
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.58. Setuptools-84.0.0  [unpack setuptools-84.0.0.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/setuptools-84.0.0.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.58.1. Installation of Setuptools
pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD

pip3 install --no-index --find-links dist setuptools

#   8.58.2. Contents of Setuptools
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.59. Meson-1.12.0  [unpack meson-1.12.0.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/meson-1.12.0.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.59.1. Installation of Meson
pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD

pip3 install --no-index --find-links dist meson
install -vDm644 data/shell-completions/bash/meson /usr/share/bash-completion/completions/meson
install -vDm644 data/shell-completions/zsh/_meson /usr/share/zsh/site-functions/_meson

#   8.59.2. Contents of Meson
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.60. Kmod-34.2  [unpack kmod-34.2.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/kmod-34.2.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.60.1. Installation of Kmod
mkdir -p build
cd       build

meson setup --prefix=/usr ..    \
            --buildtype=release \
            -D manpages=false

ninja

ninja install

#   8.60.2. Contents of Kmod
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.61. Coreutils-9.11  [unpack coreutils-9.11.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/coreutils-9.11.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.61.1. Installation of Coreutils
patch -Np1 -i ../coreutils-9.11-i18n-1.patch

autoreconf -fv
automake -af
FORCE_UNSAFE_CONFIGURE=1 ./configure \
            --prefix=/usr

make

make NON_ROOT_USERNAME=tester check-root

groupadd -g 102 dummy -U tester

chown -R tester . 

su tester -c "PATH=$PATH make -k RUN_EXPENSIVE_TESTS=yes check" \
   < /dev/null

groupdel dummy

make install

mv -v /usr/bin/chroot /usr/sbin
mv -v /usr/share/man/man1/chroot.1 /usr/share/man/man8/chroot.8
sed -i 's/"1"/"8"/' /usr/share/man/man8/chroot.8

#   8.61.2. Contents of Coreutils
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.62. Diffutils-3.12  [unpack diffutils-3.12.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/diffutils-3.12.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.62.1. Installation of Diffutils
./configure --prefix=/usr

make

make check

make install

#   8.62.2. Contents of Diffutils
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.63. Findutils-4.11.0  [unpack findutils-4.11.0.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/findutils-4.11.0.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.63.1. Installation of Findutils
./configure --prefix=/usr --localstatedir=/var/lib/locate

make

chown -R tester .
su tester -c "PATH=$PATH make check -k"

make install

#   8.63.2. Contents of Findutils
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.64. Groff-1.24.1  [unpack groff-1.24.1.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/groff-1.24.1.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.64.1. Installation of Groff
PAGE=<paper_size> ./configure --prefix=/usr

make -j1

make check

make install

#   8.64.2. Contents of Groff
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.65. GRUB-2.14  [unpack grub-2.14.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/grub-2.14.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.65.1. Installation of GRUB for BIOS
sed 's/--image-base/--nonexist-linker-option/' -i configure

./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --disable-efiemu  \
            --disable-werror

make

make install

#   8.65.2. Installation of GRUB for 64-bit UEFI
make clean

./configure --prefix=/usr       \
            --sysconfdir=/etc   \
            --target=x86_64     \
            --with-platform=efi \
            --disable-efiemu    \
            --disable-werror

make

make install

#   8.65.3. Installation of GRUB for 32-bit UEFI
make clean

./configure --prefix=/usr       \
            --sysconfdir=/etc   \
            --target=i386       \
            --with-platform=efi \
            --disable-efiemu    \
            --disable-werror

make

make install

#   8.65.4. Contents of GRUB
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.66. Gzip-1.14  [unpack gzip-1.14.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/gzip-1.14.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.66.1. Installation of Gzip
./configure --prefix=/usr

make

make check

make install

#   8.66.2. Contents of Gzip
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.67. IPRoute2-7.1.0  [unpack iproute2-7.1.0.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/iproute2-7.1.0.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.67.1. Installation of IPRoute2
sed -i /ARPD/d Makefile
rm -fv man/man8/arpd.8

make NETNS_RUN_DIR=/run/netns

make SBINDIR=/usr/sbin install

install -vDm644 COPYING README* -t /usr/share/doc/iproute2-7.1.0

#   8.67.2. Contents of IPRoute2
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.68. Kbd-2.10.0  [unpack kbd-2.10.0.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/kbd-2.10.0.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.68.1. Installation of Kbd
patch -Np1 -i ../kbd-2.10.0-backspace-1.patch

sed -i '/RESIZECONS_PROGS=/s/yes/no/' configure
sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in

./configure --prefix=/usr --disable-vlock

make

make check

make install

cp -R -v docs/doc -T /usr/share/doc/kbd-2.10.0

#   8.68.2. Contents of Kbd
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.69. Libpipeline-1.5.8  [unpack libpipeline-1.5.8.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/libpipeline-1.5.8.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.69.1. Installation of Libpipeline
./configure --prefix=/usr

make

make install

#   8.69.2. Contents of Libpipeline
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.70. Make-4.4.1  [unpack make-4.4.1.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/make-4.4.1.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.70.1. Installation of Make
./configure --prefix=/usr

make

chown -R tester .
su tester -c "PATH=$PATH make check"

make install

#   8.70.2. Contents of Make
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.71. Patch-2.8  [unpack patch-2.8.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/patch-2.8.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.71.1. Installation of Patch
./configure --prefix=/usr

make

make check

make install

#   8.71.2. Contents of Patch
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.72. Tar-1.35  [unpack tar-1.35.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/tar-1.35.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.72.1. Installation of Tar
patch -Np1 -i ../tar-1.35-acl_fix-1.patch

FORCE_UNSAFE_CONFIGURE=1  \
./configure --prefix=/usr

make

make check

make install
make -C doc install-html docdir=/usr/share/doc/tar-1.35

#   8.72.2. Contents of Tar
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.73. Texinfo-7.3  [unpack texinfo-7.3.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/texinfo-7.3.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.73.1. Installation of Texinfo
./configure --prefix=/usr

make

make check

make install

make TEXMF=/usr/share/texmf install-tex

pushd /usr/share/info
  rm -v dir
  for f in *
    do install-info $f dir 2>/dev/null
  done
popd

#   8.73.2. Contents of Texinfo
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.74. Vim-9.2.1025  [unpack vim-9.2.1025.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/vim-9.2.1025.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.74.1. Installation of Vim
echo '#define SYS_VIMRC_FILE "/etc/vimrc"' >> src/feature.h

./configure --prefix=/usr

make

chown -R tester .
sed '/test_plugin_glvs/d' -i src/testdir/Make_all.mak

su tester -c "TERM=xterm-256color LANG=en_US.UTF-8 make -j1 test" \
   &> vim-test.log

make install

ln -sv vim /usr/bin/vi
for L in  /usr/share/man/{,*/}man1/vim.1; do
    ln -sv vim.1 $(dirname $L)/vi.1
done

ln -sv ../vim/vim92/doc /usr/share/doc/vim-9.2.1025

#   8.74.2. Configuring Vim
cat > /etc/vimrc << "EOF"
" Begin /etc/vimrc

" Ensure defaults are set before customizing settings, not after
source $VIMRUNTIME/defaults.vim
let skip_defaults_vim=1

set nocompatible
set backspace=2
set mouse=
syntax on
if (&term == "xterm") || (&term == "putty")
  set background=dark
endif

" End /etc/vimrc
EOF

vim -c ':options'

#   8.74.3. Contents of Vim
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.75. MarkupSafe-3.0.3  [unpack markupsafe-3.0.3.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/markupsafe-3.0.3.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.75.1. Installation of MarkupSafe
pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD

pip3 install --no-index --find-links dist Markupsafe

#   8.75.2. Contents of MarkupSafe
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.76. Jinja2-3.1.6  [unpack jinja2-3.1.6.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/jinja2-3.1.6.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.76.1. Installation of Jinja2
pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps $PWD

pip3 install --no-index --find-links dist Jinja2

#   8.76.2. Contents of Jinja2
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.77. Systemd-261.2  [unpack systemd-261.2.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/systemd-261.2.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.77.1. Installation of systemd
sed -e 's/GROUP="render"/GROUP="video"/' \
    -e 's/GROUP="sgx", //'               \
    -i rules.d/50-udev-default.rules.in

mkdir -p build
cd       build

meson setup ..                \
      --prefix=/usr           \
      --buildtype=release     \
      -D default-dnssec=no    \
      -D firstboot=false      \
      -D install-tests=false  \
      -D ldconfig=false       \
      -D sysusers=false       \
      -D rpmmacrosdir=no      \
      -D homed=disabled       \
      -D man=disabled         \
      -D mode=release         \
      -D pamconfdir=no        \
      -D dev-kvm-mode=0660    \
      -D nobody-group=nogroup \
      -D sysupdate=disabled   \
      -D ukify=disabled       \
      -D docdir=/usr/share/doc/systemd-261.2

ninja

echo 'NAME="Linux From Scratch"' > /etc/os-release
unshare -m ninja test

ninja install

tar -xf ../../systemd-man-pages-261.2.tar.xz \
    --no-same-owner --strip-components=1     \
    -C /usr/share/man

systemd-machine-id-setup

systemctl preset-all

#   8.77.2. Contents of systemd
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.78. D-Bus-1.16.2  [unpack dbus-1.16.2.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/dbus-1.16.2.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.78.1. Installation of D-Bus
mkdir build
cd    build

meson setup --prefix=/usr --buildtype=release --wrap-mode=nofallback ..

ninja

ninja test

ninja install

ln -sfv /etc/machine-id /var/lib/dbus

#   8.78.2. Contents of D-Bus
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.79. Man-DB-2.13.1  [unpack man-db-2.13.1.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/man-db-2.13.1.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.79.1. Installation of Man-DB
./configure --prefix=/usr                         \
            --docdir=/usr/share/doc/man-db-2.13.1 \
            --sysconfdir=/etc                     \
            --disable-setuid                      \
            --enable-cache-owner=bin              \
            --with-browser=/usr/bin/lynx          \
            --with-vgrind=/usr/bin/vgrind         \
            --with-grap=/usr/bin/grap

make

make check

make install

#   8.79.2. Non-English Manual Pages in LFS
#   8.79.3. Contents of Man-DB
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.80. Procps-ng-4.0.7  [unpack procps-ng-4.0.7.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/procps-ng-4.0.7.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.80.1. Installation of Procps-ng
./configure --prefix=/usr                           \
            --docdir=/usr/share/doc/procps-ng-4.0.7 \
            --disable-static                        \
            --disable-kill                          \
            --enable-watch8bit                      \
            --with-systemd

make

chown -R tester .
su tester -c "PATH=$PATH make check"

make install

#   8.80.2. Contents of Procps-ng
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.81. Util-linux-2.42.2  [unpack util-linux-2.42.2.tar.xz]
#----------------------------------------------------------------------
_tb="/sources/util-linux-2.42.2.tar.xz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.81.1. Installation of Util-linux
./configure --bindir=/usr/bin     \
            --libdir=/usr/lib     \
            --runstatedir=/run    \
            --sbindir=/usr/sbin   \
            --disable-chfn-chsh   \
            --disable-login       \
            --disable-nologin     \
            --disable-su          \
            --disable-setpriv     \
            --disable-runuser     \
            --disable-pylibmount  \
            --disable-liblastlog2 \
            --disable-static      \
            --without-python      \
            ADJTIME_PATH=/var/lib/hwclock/adjtime \
            --docdir=/usr/share/doc/util-linux-2.42.2

make

touch /etc/fstab
chown -R tester .
su tester -c "make -k check"

make install

#   8.81.2. Contents of Util-linux
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.82. E2fsprogs-1.47.4  [unpack e2fsprogs-1.47.4.tar.gz]
#----------------------------------------------------------------------
_tb="/sources/e2fsprogs-1.47.4.tar.gz"
_dir=$(tar tf "$_tb" | awk -F/ '$1!="." && $1!=""{print $1; exit}')
tar -xf "$_tb"
cd "$_dir"
#   8.82.1. Installation of E2fsprogs
mkdir -v build
cd       build

../configure --prefix=/usr       \
             --sysconfdir=/etc   \
             --enable-elf-shlibs \
             --disable-libblkid  \
             --disable-libuuid   \
             --disable-uuidd     \
             --disable-fsck

make

make check

make install

rm -fv /usr/lib/{libcom_err,libe2p,libext2fs,libss}.a

gunzip -v /usr/share/info/libext2fs.info.gz
install-info --dir-file=/usr/share/info/dir /usr/share/info/libext2fs.info

makeinfo -o      doc/com_err.info ../lib/et/com_err.texinfo
install -v -m644 doc/com_err.info /usr/share/info
install-info --dir-file=/usr/share/info/dir /usr/share/info/com_err.info

#   8.82.2. Configuring E2fsprogs
sed 's/metadata_csum_seed,//' -i /etc/mke2fs.conf

#   8.82.3. Contents of E2fsprogs
cd "/sources"
rm -rf "$_dir"


#----------------------------------------------------------------------
# 8.83. About Debugging Symbols
#----------------------------------------------------------------------

#----------------------------------------------------------------------
# 8.84. Stripping  [runs directly]
#----------------------------------------------------------------------
save_usrlib="$(cd /usr/lib; ls ld-linux*[^g])
             libc.so.6
             libthread_db.so.1
             libquadmath.so.0.0.0
             libstdc++.so.6.0.36
             libitm.so.1.0.0
             libatomic.so.1.2.0"

cd /usr/lib

for LIB in $save_usrlib; do
    objcopy --only-keep-debug --compress-debug-sections=zstd $LIB $LIB.dbg
    cp $LIB /tmp/$LIB
    strip --strip-unneeded /tmp/$LIB
    objcopy --add-gnu-debuglink=$LIB.dbg /tmp/$LIB
    install -vm755 /tmp/$LIB /usr/lib
    rm /tmp/$LIB
done

online_usrbin="bash find strip"
online_usrlib="libbfd-2.47.20260726.so
               libsframe.so.3.0.0
               libhistory.so.8.3
               libncursesw.so.6.6
               libm.so.6
               libreadline.so.8.3
               libz.so.1.3.2
               libzstd.so.1.5.7
               $(cd /usr/lib; find libnss*.so* -type f)"

for BIN in $online_usrbin; do
    cp /usr/bin/$BIN /tmp/$BIN
    strip --strip-unneeded /tmp/$BIN
    install -vm755 /tmp/$BIN /usr/bin
    rm /tmp/$BIN
done

for LIB in $online_usrlib; do
    cp /usr/lib/$LIB /tmp/$LIB
    strip --strip-unneeded /tmp/$LIB
    install -vm755 /tmp/$LIB /usr/lib
    rm /tmp/$LIB
done

for i in $(find /usr/lib -type f -name \*.so* ! -name \*dbg) \
         $(find /usr/lib -type f -name \*.a)                 \
         $(find /usr/{bin,sbin,libexec} -type f); do
    case "$online_usrbin $online_usrlib $save_usrlib" in
        *$(basename $i)* )
            ;;
        * ) strip --strip-unneeded $i
            ;;
    esac
done

unset BIN LIB save_usrlib online_usrbin online_usrlib


#----------------------------------------------------------------------
# 8.85. Cleaning Up  [runs directly]
#----------------------------------------------------------------------
rm -rf /tmp/{*,.*}

find /usr/lib /usr/libexec -name \*.la -delete

find /usr -depth -name $(uname -m)-lfs-linux-gnu\* | xargs rm -rf

userdel -r tester

